export default [
    "BE RIGHT BACK",
    "ITS TIME TO PISS?",
    "WELCOME TO THE BRB ZONE",
    "BACK IN A SECOND",
    "GIVE ME A MINUTE TO KILL GOD",
    "STAND OUTSIDE FOR A MINUTE",
    "WAITING TIME",
    "GET SNACKIES AND SHIT",
];
