const statuses = [
    "SETTING THE FUCK UP, OKAY? DAMN. ITS LIKE YOU WANT ME TO START NOW",
    "DESTROYING MY OBS SETUP PRE-STREAM",
    "MENTALLY GETTING FUCKED ON BY THE CONTENT I NEED TO BRING YOU",
    "CHUGGING EVERY SINGLE SYRUP I HAVE. EVEN THE OLD ONES",
    "DECIDING TO MAKE COFFEE OR NOT",
    "POOP NAPPING LIKE SOME KIND OF POOP NAPPER",
    "ARGUING WITH SOMEONE IN CHAT VIA WHISPERS",
    "STUDYING KEY WIKIPEDIA ARTICLES",
    "CLEANING CANS OFF OF THE OL' DESK",
    "ASSEMBLING THE WORLDS MOST ANNOYING WOODEN KAZOO",
    "PONDERING THE ORB",
    "BECOMING INCREASINGLY LOST IN THE SAUCE",
    "LAST-MINUTE EDITING MY LATEST YOUTUBE VIDEO",
    "DEADLIFTING 7000LBS IN PREPARATION FOR STREAM",
    "MEDITATING INTENSIVELY",
    "GETTING HARD. STAYING HARD. MORTAL SHELL. FEELING WELL.",
    "LOADING THOSE HIGH POLY, LIFELIKE TEXTURES",
    "...AT LEAST YOU'RE NOT ON HOLD. FUCK BEING ON HOLD",
    "JUST COUNT TO 10 AND THEN DO IT AGAIN. COUNT TO 400 I DONT GIVE A SHIT. JUST CHILL.",
    "COUNTING BACKWARDS FROM INFINITY",
    "DON'T PANIC. JUST FUCKING WAIT. JESUS.",
    "EXPLODING SHOCKERS, SHOCKING EXPLODERS, YOU KNOW. STREAMER STUFF.",
    "A KISS IS LIKE A FIGHT WITH YOUR MOUTHS. THINK ABOUT THAT THOUGH.",
    "I'M BUSY PLAYING BOLVER, JUST ONE MORE GAME, HANG ON",
    "KROM STOLE MY PROCESSOR AND HES TRYING TO EAT IT, BRB",
    "KROM IS LITERALLY CRAWLING INTO MY PC LIKE A CAT, HOLD ON",
    "I AM SUMMONING THE ENERGY TO BRING YOU THE CONTENT",
    "PRE-CALCULATING HOW MANY TIMES I CAN SAY WELL WELL WELL TODAY",
    "FINDING OUT THE PROPER SKILL-TO-SHENANIGANS RATIO FOR TODAY",
    "SCROLLING TWITTER FOR MEMES TO STEAL",
    "FINDING OUT HOW I'M GOING TO WORK THE GODDAMN KAZOO INTO THE STREAM TODAY",
    "LAMENTING THE LACK OF SOLID ASS BROTHERGRAMS. BROTHERGRAMS ABOUT SOLID ASS.",
    "HOPPING ON THE FUCK TRUCK AND BARRELLING STRAIGHT INTO POUND TOWN (PLATONIC)",
    "AT SOME POINT I'M JUST GOING TO TURN THESE MESSAGES INTO A MARKOV BOT",
    "THE STREAMER™ WILL BE GIVING YOU YOUR CONTENT™ SOON™.",
    "HAVE I EVER TOLD YOU THE TALE OF DARTH PLAGUEIS THE WISE?",
    "IVE BEEN CHUGGING SYRUP AND SCREAMING AT THE KIDS OUTSIDE MY ROOM. IM ALMOST READY.",
    "TAKE THIS TIME TO REFLECT ON WHY YOURE HERE AND WHAT YOU'VE DONE.",
];

const spooky = [
    "SPOOKY SCARY MORK IS SWIGGITY SWOOTY SWINGIN HIS BOOTY",
    "WELCOME TO THE BONE ZONE, FOR STREAMING. BONING. STREAM-BONING.",
    "IM MORKLYMPI S. PUMPKINS, AND IM HERE TO SCARE THE HELL OUT OF YOU",
];

const holiday = [
    "ITS BEGINNING TO LOOK A LOT LIKE MORKSMAS",
    "JINGLE BELL JINGLE BELL JINGLE BELL MORK",
    "IM DREAMING OF MORK SLAMMING DOWN MY CHIMNEY AND SCREAMING",
    "REMEMBER TO LEAVE MORK AND COOKIES OUT FOR MR. CLAUS",
    "THIS IS ONE FUCKING CONTENT CREATOR THATS SHITTING, PISSING, AND OOZING CRIMMINS SPIRIT",
    "KROM JUST CHUGGED TOO MUCH EGG NOG AND HE WONT STOP BURPING. ONE SECOND",
    "THINKING ABOUT PUTTING UP A TREE AND THEN JUST... LEAVING IT ALL YEAR.",
    "ENJOYING SOME OF KROM MOMS FRESHLY BAKED HOLIDAY KROOKIES",
    "KROM WONT STOP TRYING TO 'HUNT' SANTA. GOD DAMMIT",
    "YOU KNOW WHAT THE HOLIDAYS NEED MORE OF? SKELETONS. BONE-LADS.",
    "FLIPPING THROUGH THE NORDIC CHAINSAW CATALOG, KROM WANTS A CHAINSAW",
];

export { spooky, holiday };

export default statuses;
